In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

df = pd.read_csv("../data/processed/customer_features.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (5000, 12)

,customer_id,age,tenure_months,monthly_charges,total_purchases,avg_transaction_value,support_tickets,churn,estimated_lifetime_value,estimated_total_spending,support_ticket_rate,purchase_frequency
0,100001,56,9,3618.14,94,5060.17,1,0,32563.26,475655.98,0.100000,9.400000
1,100002,69,37,4943.16,58,8129.98,1,0,182896.92,471538.84,0.026316,1.526316
2,100003,46,74,1513.22,8,3538.63,4,0,111978.28,28309.04,0.053333,0.106667
3,100004,32,36,3480.43,42,4013.77,2,0,125295.48,168578.34,0.054054,1.135135
4,100005,60,101,3243.57,76,7607.56,1,0,327600.57,578174.56,0.009804,0.745098

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               5000 non-null   int64
 1   age                       5000 non-null   int64
 2   tenure_months             5000 non-null   int64
 3   monthly_charges           5000 non-null   float64
 4   total_purchases           5000 non-null   int64
 5   avg_transaction_value     5000 non-null   float64
 6   support_tickets           5000 non-null   int64
 7   churn                     5000 non-null   int64
 8   estimated_lifetime_value  5000 non-null   float64
 9   estimated_total_spending  5000 non-null   float64
 10  support_ticket_rate       5000 non-null   float64
 11  purchase_frequency        5000 non-null   float64
dtypes: float64(6), int64(6)
memory usage: 468.9 KB

In [4]:
df.describe()

,customer_id,age,tenure_months,monthly_charges,total_purchases,avg_transaction_value,support_tickets,churn,estimated_lifetime_value,estimated_total_spending,support_ticket_rate,purchase_frequency
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,102500.500000,46.148600,60.804200,2717.614544,49.379200,5053.205190,2.030400,0.146600,165796.862746,249509.656870,0.073046,1.743914
std,1443.520003,16.325753,34.375913,1286.839486,28.577347,2732.892359,1.436624,0.353742,130828.349825,212702.130289,0.176502,3.623699
min,100001.000000,18.000000,1.000000,500.240000,1.000000,200.090000,0.000000,0.000000,501.080000,331.860000,0.000000,0.008772
25%,101250.750000,32.000000,31.000000,1610.295000,24.000000,2762.672500,1.000000,0.000000,60302.625000,74181.775000,0.014706,0.400000
50%,102500.500000,46.000000,61.000000,2707.030000,50.000000,5039.225000,2.000000,0.000000,130568.070000,188212.015000,0.031250,0.800000
75%,103750.250000,60.000000,90.000000,3812.100000,74.000000,7298.945000,3.000000,0.000000,244713.887500,374565.175000,0.063241,1.523260
max,105000.000000,74.000000,120.000000,4997.770000,99.000000,9998.950000,10.000000,1.000000,593720.400000,961673.020000,5.000000,47.500000

In [5]:
print("Churn Counts:")
print(df["churn"].value_counts())

print("\nChurn Percentage:")
churn_percentage = df["churn"].value_counts(normalize=True) * 100
print(churn_percentage)

Churn Counts:
churn
0    4267
1     733
Name: count, dtype: int64

Churn Percentage:
churn
0    85.34
1    14.66
Name: proportion, dtype: float64

Correlation Analysis

In [6]:
# Calculate correlation with churn
correlation = df.corr(numeric_only=True)

churn_correlation = (
    correlation["churn"]
    .sort_values(ascending=False)
)

print("Correlation of Features with Churn:")
print(churn_correlation)

Correlation of Features with Churn:
churn                       1.000000
support_tickets             0.105775
support_ticket_rate         0.078898
purchase_frequency          0.030254
age                         0.025808
avg_transaction_value       0.004681
customer_id                 0.003363
estimated_total_spending   -0.008417
total_purchases            -0.009319
monthly_charges            -0.011871
estimated_lifetime_value   -0.084925
tenure_months              -0.107610
Name: churn, dtype: float64

Hypothesis Testing

In [7]:
# Compare tenure between churned and non-churned customers

churned_tenure = df[df["churn"] == 1]["tenure_months"]
non_churned_tenure = df[df["churn"] == 0]["tenure_months"]

t_stat, p_value = stats.ttest_ind(
    churned_tenure,
    non_churned_tenure,
    equal_var=False
)

print("Churned Customer Average Tenure:",
      round(churned_tenure.mean(), 2))

print("Non-Churned Customer Average Tenure:",
      round(non_churned_tenure.mean(), 2))

print("T-statistic:", round(t_stat, 4))
print("P-value:", p_value)

if p_value < 0.05:
    print("\nResult: Statistically significant difference detected.")
else:
    print("\nResult: No statistically significant difference detected.")

Churned Customer Average Tenure: 51.88
Non-Churned Customer Average Tenure: 62.34
T-statistic: -7.7253
P-value: 2.6872465810725865e-14

Result: Statistically significant difference detected.

Analyze Support Tickets

In [8]:
# Compare support tickets between churned and non-churned customers

churned_tickets = df[df["churn"] == 1]["support_tickets"]
non_churned_tickets = df[df["churn"] == 0]["support_tickets"]

t_stat, p_value = stats.ttest_ind(
    churned_tickets,
    non_churned_tickets,
    equal_var=False
)

print(
    "Churned Customer Average Support Tickets:",
    round(churned_tickets.mean(), 2)
)

print(
    "Non-Churned Customer Average Support Tickets:",
    round(non_churned_tickets.mean(), 2)
)

print("T-statistic:", round(t_stat, 4))
print("P-value:", p_value)

if p_value < 0.05:
    print("\nResult: Statistically significant difference detected.")
else:
    print("\nResult: No statistically significant difference detected.")

Churned Customer Average Support Tickets: 2.4
Non-Churned Customer Average Support Tickets: 1.97
T-statistic: 6.948
P-value: 6.89976638574487e-12

Result: Statistically significant difference detected.

In [9]:
# Calculate correlation with churn
correlation = df.corr(numeric_only=True)

churn_correlation = (
    correlation["churn"]
    .sort_values(ascending=False)
)

print("Correlation of Features with Churn:")
print(churn_correlation)

Correlation of Features with Churn:
churn                       1.000000
support_tickets             0.105775
support_ticket_rate         0.078898
purchase_frequency          0.030254
age                         0.025808
avg_transaction_value       0.004681
customer_id                 0.003363
estimated_total_spending   -0.008417
total_purchases            -0.009319
monthly_charges            -0.011871
estimated_lifetime_value   -0.084925
tenure_months              -0.107610
Name: churn, dtype: float64

In [10]:
# Compare support tickets between churned and non-churned customers

churned_tickets = df[df["churn"] == 1]["support_tickets"]
non_churned_tickets = df[df["churn"] == 0]["support_tickets"]

t_stat, p_value = stats.ttest_ind(
    churned_tickets,
    non_churned_tickets,
    equal_var=False
)

print(
    "Churned Customer Average Support Tickets:",
    round(churned_tickets.mean(), 2)
)

print(
    "Non-Churned Customer Average Support Tickets:",
    round(non_churned_tickets.mean(), 2)
)

print("T-statistic:", round(t_stat, 4))
print("P-value:", p_value)

if p_value < 0.05:
    print("\nResult: Statistically significant difference detected.")
else:
    print("\nResult: No statistically significant difference detected.")

Churned Customer Average Support Tickets: 2.4
Non-Churned Customer Average Support Tickets: 1.97
T-statistic: 6.948
P-value: 6.89976638574487e-12

Result: Statistically significant difference detected.

Machine Learning